;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("source"
  (filename . "~/source/")
  (front-context-string)
  (rear-context-string . "0K sep 16 17:39 ")
  (position . 174)
  (last-modified 27312 25196 544350 975000))
("personal-study"
 (filename . "~/org/2_areas/kingdom/personal-study/")
 (front-context-string . "20260808211957-t")
 (rear-context-string . "91 sep 14 21:19 ")
 (position . 292)
 (last-modified 27304 40382 1916 455000))
("resources"
 (filename . "~/org/3_resources/")
 (front-context-string . "ltximg\n  -rw-r--")
 (rear-context-string . "0K sep 14 21:19 ")
 (position . 180)
 (last-modified 27308 39760 72093 879000))
("org"
 (filename . "~/org/")
 (front-context-string . "1_projects\n  drw")
 (rear-context-string . "0K sep 14 21:19 ")
 (position . 171)
 (last-modified 27304 40353 969463 431000))
("init.el"
 (filename . "~/.emacs.d/init.el")
 (front-context-string . ";; -*- lexical-b")
 (rear-context-string)
 (position . 1)
 (last-modified 27304 40190 721173 343000))
)
